name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code formatting
        run: find src include tests \( -name "*.cpp" -o -name "*.h" \) | xargs clang-format --dry-run --Werror

  style-check:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform style analysis (src)
        run: clang-tidy -p build src/*.cpp -- -std=c++20 -Ibuild/_deps/catch2-src/src/ -Iinclude -Ibuild/_deps/catch2-build/generated-includes

      - name: Perform style analysis (tests)
        run: clang-tidy -p build $(find tests -name "*.cpp") -- -std=c++20 -Ibuild/_deps/catch2-src/src/ -Iinclude -Ibuild/_deps/catch2-build/generated-includes

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake project with tests enabled
        run: cmake -DENABLE_TESTS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build

      - name: Build the tests
        run: cmake --build build

      - name: Run the tests
        run: ./build/tests/test
